site_name: Interação Humano Computador - Estagiários.com

repo_name: ""
repo_url: ""

nav: 
  - Home: index.md
  - Planejamento: 
      - Planejamento: planejamento/planejamento.md
      - Ferramentas: planejamento/ferramentas.md

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/favicon.ico
  language: pt
  palette:
    primary: green