site_name: Interação Humano Computador - Site Estagiarios.com

repo_name: ""
repo_url: ""

nav:
  - Home: index.md
  - Planejamento:
      - Planejamento: planejamento/planejamento.md
      - Ferramentas: planejamento/ferramentas.md
  - Perfil do Usuário:
      - Personas: perfil_usuario/personas.md
      - Questionário: perfil_usuario/questionario.md
      - Perfil de Usuário: perfil_usuario/perfil.md
  - Pontos de Controle: pontos_de_controle/pontos_de_controle.md
  - Análise de Tarefas: 
      - Análise de tarefas v2: analise_tarefas/analise_tarefas_v2.md
      - Análise de tarefas v1: analise_tarefas/analise_tarefas.md      
  - Princípios Gerais de Projeto: principios_gerais/principios_gerais.md
  - Metas de Usabilidade: metas_usabilidade/metas_usabilidade.md
  - Guia de Estilo: guia_de_estilo/guia_de_estilo.md
  - Storyboards: storyboard/storyboard.md

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/favicon.ico
  language: pt
  palette:
    primary: green
