site_name: Interação Humano Computador - Site Estagiarios.com

repo_name: ""
repo_url: ""

nav:
  - Home: index.md
  - Planejamento:
      - Planejamento: planejamento/planejamento.md
      - Ferramentas: planejamento/ferramentas.md
  - Perfil do Usuário:
      - Personas: perfil_usuario/personas.md
      - Questionário: perfil_usuario/questionario.md
      - Perfil de Usuário: perfil_usuario/perfil.md
  - Análise de Tarefas: analise_tarefas/analise_tarefas.md

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/favicon.ico
  language: pt
  palette:
    primary: green
